/// One row of `_omer_mapping.json`.
///
/// Generated by `scripts/phase_d7.js` from the EM Sefirat HaOmer source
/// (which contains the standard Sephardic Kabbalistic per-day mapping).
/// Loaded at runtime by [IOmerMappingRepository] and consumed by
/// [PrayerAssembler] to fill placeholders and inject bold-token highlights
/// into the Sefirat HaOmer segments.
class OmerDay {
  const OmerDay({
    required this.day,
    required this.week,
    required this.dayInWeek,
    required this.textAshkenaz,
    required this.textSfard,
    required this.textEdotMizrach,
    required this.sefira,
    required this.anaWord,
    required this.lamenatzeachWord,
    required this.yismechuLetter,
  });

  /// 1..49
  final int day;

  /// 1..7 (which of the 7 weeks of the counting)
  final int week;

  /// 1..7 (which day within the week — 7 = end of week, acronym day)
  final int dayInWeek;

  /// Counting text per nusach (fully vocalized).
  /// e.g. "הַיּוֹם יוֹם אֶחָד בָּעֹֽמֶר:" (Ashk)
  ///   /  "הַיּוֹם יוֹם אֶחָד לָעֹֽמֶר:" (Sfard, EM)
  final String textAshkenaz;
  final String textSfard;
  final String textEdotMizrach;

  /// Vocalized sefira name (e.g. "חֶסֶד שֶׁבְּחֶסֶד").
  /// Used to fill the {{omer_sefira}} placeholder in Ribono Shel Olam.
  final String sefira;

  /// Bare (unvocalized) word from Ana BeKoach corresponding to this day,
  /// or the line acronym on end-of-week days (e.g. 'אנא' or 'אב"ג ית"ץ').
  final String anaWord;

  /// Bare (unvocalized) word from Lamenatzeach (Psalm 67) corresponding to
  /// this day's sequential position (1..49 word after the heading).
  final String lamenatzeachWord;

  /// The single highlighted letter from the verse
  /// "יִשְׂמְחוּ וִירַנְּנוּ לְאֻמִּים..." at position [day - 1].
  final String yismechuLetter;

  /// Returns the counting text matching the given nusach key.
  String textFor(String nusach) {
    switch (nusach) {
      case 'ashkenaz':
        return textAshkenaz;
      case 'sfard':
        return textSfard;
      case 'edot_mizrach':
        return textEdotMizrach;
      default:
        // Unknown nusach: default to Sfard.
        return textSfard;
    }
  }

  factory OmerDay.fromJson(Map<String, dynamic> json) => OmerDay(
        day: json['day'] as int,
        week: json['week'] as int,
        dayInWeek: json['day_in_week'] as int,
        textAshkenaz: json['text_ashkenaz'] as String,
        textSfard: json['text_sfard'] as String,
        textEdotMizrach: json['text_edot_mizrach'] as String,
        sefira: json['sefira'] as String,
        anaWord: json['ana_word'] as String,
        lamenatzeachWord: json['lamenatzeach_word'] as String,
        yismechuLetter: json['yismechu_letter'] as String,
      );
}
