/// One row of `_sukkot_korbanot_mapping.json`.
///
/// Generated by `scripts/phase_d12fg.js` from the standard Sefirat HaOmer
/// Sukkot Musaf source (Numbers 29). Loaded at runtime by
/// [ISukkotKorbanotRepository] and consumed by [SukkotKorbanotPostProcessor]
/// to fill the `{{daily_korban}}` placeholder in
/// `amidah_musaf_intermediate_chm_sukkot`.
class SukkotKorban {
  const SukkotKorban({
    required this.day,
    required this.pasukIsrael,
    required this.pasukChul,
    this.note,
  });

  /// 1..7 (sukkot day; 1 = Yom Tov, 2..6 = Chol HaMoed, 7 = Hoshana Raba).
  final int day;

  /// Korban pasuk recited in Israel.
  final String pasukIsrael;

  /// Korban pasuk recited in Diaspora — doubles up via s'feika d'yoma on
  /// CHM days 3..7 (recites prior day + current day).
  final String pasukChul;

  /// Optional note (e.g. empty placeholder when content is out of scope).
  final String? note;

  String textFor({required bool isInIsrael}) =>
      isInIsrael ? pasukIsrael : pasukChul;

  factory SukkotKorban.fromJson(Map<String, dynamic> json) => SukkotKorban(
        day: json['day'] as int,
        pasukIsrael: (json['pasuk_israel'] ?? '') as String,
        pasukChul: (json['pasuk_chu_l'] ?? '') as String,
        note: json['note'] as String?,
      );
}
